server {
    listen 80;
    server_name localhost;
    include /etc/nginx/mime.types;

    # Statische Dateien
    location /static/ {
        root /usr/share/nginx/html;
        autoindex off;
    }

    location /src/ {
        root /usr/share/nginx/html;
        autoindex off;
    }

    location /assets/ {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types;
        autoindex off;
        # MIME-Type Fix für 3D Modelle
        types {
            model/gltf-binary glb;
            model/gltf+json gltf;
        }
    }

    # Audio Dateien vom TTS Server laden
    location /audio/ {
        proxy_pass http://tts-server:5002;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API Proxy
    location /chat {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
